### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by kentr** [MazeMap/Leaflet.TileLayer.PouchDBCached#14]
The [demo](http://mazemap.github.io/Leaflet.TileLayer.PouchDBCached/demo.html) has an invalid URL for pouchdb.js

```
"NetworkError: 404 Not Found - http://mazemap.github.io/Leaflet.TileLayer.PouchDBCached/bower_components/pouchdb/dist/pouchdb.js"
pouchdb.js
ReferenceError: PouchDB is not defined
```

Additionally, when that link is fixed to point to a working pouchdb.js, the seed demo fails, seemingly because of #9.

```
TypeError: this._getTileSize is not a function
var tileSize   = this._getTileSize();
L.TileL...ched.js (line 154, col 21)
```

**Comment by nikolauskrismer** [comment]
Both issues should be fixed.
If that is still an issue for you please re-open
